import type { Metadata } from "next";

import RecoilRootWrapper from "../shared/utils/RecoilWrapper";

export const metadata: Metadata = {
  title: "Next Study",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilRootWrapper>{children}</RecoilRootWrapper>
      </body>
    </html>
  );
}
